apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: todo-bot
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/mattmoor/todo-bot/cmd/hook
            env:
            - name: GITHUB_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-comment-secret
                  key: accessToken
