apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: todo-bot-subscription
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: todo-bot-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: todo-bot
